#!/bin/bash

case "$1" in
    configure|triggered)

        /usr/share/kaisen-menu/scripts/update-kaisen-menu
	/usr/share/kaisen-menu/scripts/kaisen-basemenu-purge

	if [ ! -d /usr/share/kaisen-services-management ]; then
		rm -f /usr/share/applications/{kaisen*-disable.desktop,kaisen*-enable.desktop}
	fi
esac
