#!/bin/bash

set -e

if [[ "$1" = "remove" ]]; then
	find /usr/share/applications -name '*.desktop' | \
	    xargs grep -l ^X-Kaisen-Package | \
	    xargs rm -f || true
fi

if [[ "$1" = "purge" ]]; then

if [[ -e /etc/xdg/menus/mate-applications.menu.old ]]; then
	mv /etc/xdg/menus/mate-applications.menu.old /etc/xdg/menus/mate-applications.menu
fi

if [[ -e /etc/xdg/menus/xfce-applications.menu.old ]]; then
	mv /etc/xdg/menus/xfce-applications.menu.old /etc/xdg/menus/xfce-applications.menu
fi
        dpkg-divert --quiet --no-rename --package kaisen-menu --divert /etc/xdg/menus/mate-applications.menu.old --remove /etc/xdg/menus/mate-applications.menu
        dpkg-divert --quiet --no-rename --package kaisen-menu --divert /etc/xdg/menus/xfce-applications.menu.old --remove /etc/xdg/menus/xfce-applications.menu
fi

#DEBHELPER#
