#!/bin/bash

case "$1" in
    configure|triggered)

        /usr/share/kaisen-menu/scripts/kaisen-menu-update
	/usr/share/kaisen-menu/scripts/kaisen-basemenu-purge

	if [ ! -d /usr/share/kaisen-services-management ]; then
		rm -f /usr/share/applications/{kaisen*-disable.desktop,kaisen*-enable.desktop}
	fi

	# Force the update of the menu
	xdg-desktop-menu forceupdate
esac
