#!/bin/bash

set -e

dpkg-divert --quiet --package kaisen-menu --divert /etc/xdg/menus/xfce-applications.menu.old --rename /etc/xdg/menus/xfce-applications.menu || true
dpkg-divert --quiet --package kaisen-menu --divert /etc/xdg/menus/mate-applications.menu.old --rename /etc/xdg/menus/mate-applications.menu || true

#DEBHELPER#
