#!/bin/bash

set -e

if [[ -z "$2" ]]; then

if [[ -e /etc/xdg/menus/mate-applications.menu ]]; then
	mv /etc/xdg/menus/mate-applications.menu /etc/xdg/menus/mate-applications.menu.old
fi

if [[ -e /etc/xdg/menus/xfce-applications.menu ]]; then
	mv /etc/xdg/menus/xfce-applications.menu /etc/xdg/menus/xfce-applications.old
fi
	dpkg-divert --quiet --no-rename --package kaisen-menu --divert /etc/xdg/menus/xfce-applications.menu.old --add /etc/xdg/menus/xfce-applications.menu
	dpkg-divert --quiet --no-rename --package kaisen-menu --divert /etc/xdg/menus/mate-applications.menu.old --add /etc/xdg/menus/mate-applications.menu
fi

case "$1" in
	upgrade|dist-upgrade|full-upgrade)
		if dpkg --compare-versions "$2" lt 2.0+kaisen9; then
			dpkg-divert --quiet --no-rename --package kaisen-menu --divert /etc/xdg/menus/xfce-applications.menu.old --add /etc/xdg/menus/xfce-applications.menu
        		dpkg-divert --quiet --no-rename --package kaisen-menu --divert /etc/xdg/menus/mate-applications.menu.old --add /etc/xdg/menus/mate-applications.menu
		fi
	;;
esac

#DEBHELPER#
