#!/bin/bash

set -e

case "$1" in
        purge|remove|autoremove)
                #Remove diversion
		dpkg-divert --quiet --no-rename --remove /etc/xdg/menus/mate-applications.menu
		dpkg-divert --quiet --no-rename --remove /etc/xdg/menus/xfce-applications.menu
	;;
esac

#DEBHELPER#
