#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

rm -f /usr/share/applications/balena-etcher-electron.desktop
rm -f /usr/share/applications/bat.desktop
rm -f /usr/share/applications/bleachbit-root.desktop
rm -f /usr/share/applications/clamtk.desktop
rm -f /usr/share/applications/clamtk-kde.desktop
rm -f /usr/share/applications/clusterssh.desktop
rm -f /usr/share/applications/codium.desktop
rm -f /usr/share/applications/codium-url-handler.desktop
rm -f /usr/share/applications/conky.desktop
rm -f /usr/share/applications/cpu-x.desktop
rm -f /usr/share/applications/debian-uxterm.desktop
rm -f /usr/share/applications/debian-xterm.desktop
rm -f /usr/share/applications/ddrescue-gui.desktop
rm -f /usr/share/applications/ddrescueview.desktop
rm -f /usr/share/applications/designer-qt5.desktop
rm -f /usr/share/applications/driftnet.desktop
rm -f /usr/share/applications/ettercap.desktop
rm -f /usr/share/applications/etherape.desktop
rm -f /usr/share/applications/filezilla.desktop
rm -f /usr/share/applications/firefox-esr.desktop
rm -f /usr/share/applications/gftp.desktop
rm -f /usr/share/applications/gparted.desktop
rm -f /usr/share/applications/grdesktop.desktop
rm -f /usr/share/applications/grsync.desktop
rm -f /usr/share/applications/gsmartcontrol.desktop
rm -f /usr/share/applications/guymager.desktop
rm -f /usr/share/applications/hardinfo.desktop
rm -f /usr/share/applications/htop.desktop
rm -f /usr/share/applications/hydra-gtk.desktop
rm -f /usr/share/applications/jmeter.desktop
rm -f /usr/share/applications/kismet.desktop
rm -f /usr/share/applications/lftp.desktop
rm -f /usr/share/applications/linguist-qt5.desktop
rm -f /usr/share/applications/lshw-gtk.desktop
rm -f /usr/share/applications/lstopo.desktop
rm -f /usr/share/applications/mc.desktop
rm -f /usr/share/applications/mcedit.desktop
rm -f /usr/share/applications/mutt.desktop
rm -f /usr/share/applications/minicom.desktop
rm -f /usr/share/applications/kde4/nmapsi4-admin.desktop
rm -f /usr/share/applications/kde4/nmapsi4.desktop
rm -f /usr/share/applications/ophcrack.desktop
rm -f /usr/share/applications/org.bleachbit.BleachBit.desktop
rm -f /usr/share/applications/org.gnome.baobab.desktop
rm -f /usr/share/applications/org.keepassxc.KeePassXC.desktop
rm -f /usr/share/applications/org.remmina.Remmina.desktop
rm -f /usr/share/applications/org.wireshark.Wireshark.desktop
rm -f /usr/share/applications/packeth.desktop
rm -f /usr/share/applications/packetsender.desktop
rm -f /usr/share/applications/qemu.desktop
rm -f /usr/share/applications/qtop.desktop
rm -f /usr/share/applications/R.desktop
rm -f /usr/share/applications/remote-viewer.desktop
rm -f /usr/share/applications/remmina-file.desktop
rm -f /usr/share/applications/remmina-gnome.desktop
rm -f /usr/share/applications/terminator.desktop
rm -f /usr/share/applications/timeshift-gtk.desktop
rm -f /usr/share/applications/virt-manager.desktop
rm -f /usr/share/applications/virtualbox.desktop
rm -f /usr/share/applications/wireshark.desktop
rm -f /usr/share/applications/xca.desktop
rm -f /usr/share/applications/xsensors.desktop
rm -f /usr/share/applications/zulucrypt-gui.desktop
rm -f /usr/share/applications/zulumount-gui.desktop
